apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1  # The desired number of MySQL replicas
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql-image:tag # The MySQL image you wish to use
        ports:
        - containerPort: 3306  # MySQL port
        resources:
          limits:
            memory: "512Mi"   # Maximum memory limit
            cpu: "1"           # Maximum CPU usage limit
          requests:
            memory: "256Mi"   # Minimum memory request
            cpu: "0.5"         # Minimum CPU usage request
       # env:
        #  - name: MYSQL_ROOT_PASSWORD
        #    value: your-root-password  # Change this to your root password
        #  - name: MYSQL_DATABASE
        #    value: your-database-name  # Change this to your database name
        readinessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "mysqladmin ping -h 127.0.0.1 -u MYSQL_USER -p MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 5  # Initial delay before starting readiness probes
          periodSeconds: 10  # Frequency of readiness probes
        livenessProbe:
          exec:
            command:
            - "sh"
            - "-c"
            - "mysqladmin ping -h 127.0.0.1 -u MYSQL_USER -p MYSQL_ROOT_PASSWORD"
          initialDelaySeconds: 15  # Initial delay before starting liveness probes
          periodSeconds: 10  # Frequency of liveness probes
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql  # Directory where persistent storage will be mounted
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc  # Name of the PVC you want to mount

